### ISSUE TITLE
Ignore errors

### ISSUE THREAD

**Issue by frontierpsycho** [jeffbski/bench-rest#13]
I think it would be useful to have a feature whereby errors are ignored. The use case: I want to measure my server's overall performance, in the presence of errors, because the code path in that case is different and it might change the results.

**Comment by frontierpsycho** [comment]
No, wait, I think I wasn't entirely clear. I think the change I'm suggesting is a lot simpler. I'm not saying you should change how the stats library measures stats. I had a flow with four requests, and the second one was supposed to fail, and I think that the third and the fourth one never happened, as the entire flow was cancelled when an error was encountered. Is that not how it works? Am I wrong?

**Comment by jeffbski** [comment]
Thanks for explaining your question. I misunderstood what you were asking.

Yes, the default is that if an error status is returned it won't continue with the rest of the flow items.

However you can modify that behavior by also specifying a post operation. I have a few built in operations provided or you can write your own. 

https://github.com/jeffbski/bench-rest#prepost-operation-processing

In your case if you wanted to ignore the status code and continue regardless, you can write something like: 

```javascript
//This causes the flow to continue regardless of the status code 
// returned by the GET operation
{ get: 'http://localhost:8000', afterHooks: ['ignoreStatus'] }
```

Hopefully this is just what you need. Otherwise it is pretty easy to write your own hook functions and use them. You can use my ignoreStatus one as a starting place.

Let me know if this helps or you have additional questions.

**Comment by frontierpsycho** [comment]
Yes, this is exactly what I needed, sorry for not reading the docs thoroughly enough!

**Comment by jeffbski** [comment]
Fantastic!
