### ISSUE TITLE
  Worst performance results than ab

### ISSUE THREAD

**Issue by jgato** [jeffbski/bench-rest#7]
Hi @jeffbski ,

I need to make really hard performance test against a node with express services. Doing an initial test against a hello world service I have very significant differences between using loadtest and the traditional ab

(By the way, I am trying bench-rest after testing [loadtest](https://github.com/alexfernandez/loadtest/issues/47). I also found different results than using ab -Apache Benchmark).

Testing a "Hello World" get service with ab:

![captura de pantalla de 2015-03-09 16 13 38](https://cloud.githubusercontent.com/assets/3435696/6557743/a3ad30a0-c677-11e4-90ca-0a4a1ecf0170.png)

The same using bench-rest:

![captura de pantalla de 2015-03-09 16 17 24](https://cloud.githubusercontent.com/assets/3435696/6557762/c9ab93a0-c677-11e4-8390-d5b82930f1c0.png)

With bench-rest I have 4x less requests per second than using ab? Do you know why is this happening?

best regards,

**Comment by jeffbski** [comment]
@jgato I think the difference between AB and bench-rest must lie in the fact that it is written in C and is doing less logic (validation and other checks) per iteration. For instance bench-rest is designed to allow you to define a flow of many requests and it can do validations on things while AB doesn't. bench-rest also creates a separate cookie jar for managing cookies as you go through a flow, so if you login and get a session cookie, it and all the values for the session are with you as you do other requests.

As far as I know, AB doesn't do any of this, it just creates an HTTP request, then forgets about it and creates another.

I'm assuming your hello service is pretty minimal, probably not doing much I/O or anything involving latency. Normally with any realistic service (that talks to databases and such) there is much more I/O and latency involved and these differences go away.

Benchmarking can vary all over the map depending on different types of conditions, however what I would suggest is that what is important is how it trends over time using the same tools. So use whatever tool you want and just measure whether things are going up or down and by how much.

If you want to define a flow and lots of chained interactions then I think bench-rest can do a good job helping you watch the trends. Yes other tools which do less might achieve higher dumb transaction rates, but in a realistic service, it usually isn't the main bottleneck.

So if you need highest single transaction rate, use AB or maybe https://github.com/wg/wrk which is multi-threaded and might be a better choice. wrk can also do flows I believe but you need to create your flows in lua rather than javascript.

Normally in real world conditions, bench-rest can pound the servers quite nicely and give you all the nice flow definition capabilities while still using javascript. If not, go with wrk and use lua to script.

**Comment by jgato** [comment]
Thanks for so detailed response, I think that you are right: "no hello world services provide similar results". I have a questions, if I use you module without complicated flows, cookies, etc.. is bench-rest doing "extra job" that could affect significantly in the results? 

What I have in mind is to create some automatic incremental requests (tests). From a test base (5000 req, 100 client) create consecutive tests increasing these parameters. Finally, output some charts with the results to guess the performance peeks of the server. Do you recommend me to use your flows? is it good to create a sequence of maybe 100 tests? Currently, I am using async.eachSeries to execute each test. 

Going back to the comparative of ab and loadtest, now I am posting some content to the server and the result is much more similar:

Post request (no local) with ab 50000 req with 1000 clients:

![captura de pantalla de 2015-03-10 10 18 50](https://cloud.githubusercontent.com/assets/3435696/6572075/484c6eea-c70f-11e4-90a3-fbe5db027fc9.png)

Post request (no local) with bench-rest 50000 req with 1000 clients:

![captura de pantalla de 2015-03-10 10 20 41](https://cloud.githubusercontent.com/assets/3435696/6572077/51426752-c70f-11e4-9408-fada2c8e65e5.png)

Close enough :dancers:

**Comment by jeffbski** [comment]
I think the main question to ask with regards to using bench-rest versus something else, is whether the client is at max cpu when it is running. If your bench-rest client is at 100% cpu, then it is possible that the extra logic and overhead of running JS could be affecting your outcomes.

If the client is not at 100% and it is able to achieve the concurrency you desire, then bench-rest should not be materially affecting your results. It shows that there is still room for more (cpu is not maxed) if the server could handle it. So basically between all the requests the client is waiting long enough to be able to do its validation and garbage collection. In this case, I would feel pretty comfortable that bench-rest is influencing the outcomes and you should be able to use it to determine trends or comparisons.

With the key factor being cpu utilization for the client process, the horsepower you have running the client  can be something to consider. If you are running the client on a slow cpu, then you will hit 100% cpu sooner, however on a beefy machine, you can create a whole lot more load. Thus you will want to run your client on a machine with ample power to test your peak loads. And if you are trying to judge trends over time, you will want to keep as many of these environmental pieces the same (always use same client, network, server, etc.), so future runs are comparable to previous.

So short answer is: if your bench-rest client cpu utilization is not 100% on that process, then I don't believe bench-rest is materially affecting your results. If it is 100% on that process, then bench-rest could be a bottleneck and you would want to use a faster client or a different test runner.

**Comment by jeffbski** [comment]
I'm going to close this for now since I believe we have completed discussions regarding this. We can always reopen later if further discussion is needed.
